#!/usr/bin/env python
# coding: utf-8

# In[1]:


import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Example data
x = [1.2, 2.3, 3.4, 4.1, 5.7]
y = [3.4, 4.5, 2.2, 1.8, 6.3]
z = [7.8, 8.7, 6.6, 9.9, 2.1]
size = [50, 100, 80, 60, 90]  # Optional
color = [0, 1, 2, 3, 4]       # Optional

# Create a 3D scatter plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(x, y, z, c=color, s=size, cmap='viridis')

# Set labels
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
ax.set_zlabel('Z axis')
plt.title('3D Scatter Plot')
plt.savefig("3D scatter plot")

plt.show()


# In[2]:


# Example data
a = [10.5, 14.1, 18.2, 22.5, 25.0]
b = [8.3, 6.7, 5.9, 4.1, 7.3]
sie = [50, 120, 200, 80, 100]  # Bubble sizes
color = [1, 2, 3, 1, 2]  # Optional color variable

# Create bubble plot
plt.figure(figsize=(10, 6))
plt.scatter(a, b, s=sie, c=color, alpha=0.6, cmap='viridis')

# Add labels and title
plt.xlabel('X axis')
plt.ylabel('Y axis')
plt.title('Bubble Plot Example')

# Show color bar if needed
plt.colorbar(label='Color scale')
plt.savefig("bubble plot")

plt.show()


# In[ ]:




